defaults:
  - override hydra/launcher: slurm_launcher
  - _self_

ALGORITHM: "MAPPO"

LR: 2e-3
NUM_ENVS: 128 
NUM_STEPS: 128 # must be 128
TOTAL_TIMESTEPS: 2e6
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ACTIVATION: "tanh"

SEED: 1
NUM_SEEDS: 2
ENV_KWARGS: {}
ANNEAL_LR: True

ENV_NAME: "MimicryCommEnvGridworld"
GRID_SIZE: 10
N_AGENTS: 2
N_PREY: 1
N_TOTAL_SOUNDS: 20
N_OVERLAPPING_SOUNDS: 0

# WandB Params
WANDB_MODE: "online"
ENTITY: "drcope"
PROJECT: "jaxmarl-mpe"

# Checkpointing
CHECKPOINT_INTERVAL: 20
KEEP_CHECKPOINTS: 3