defaults:
  - override hydra/launcher: slurm_launcher
  - _self_

ALGORITHM: "EVO"

NUM_ENVS: 16 
NUM_STEPS: 256
TOTAL_GENERATIONS: 10000
POP_SIZE: 256
EVO_STRATEGY: "SimpleGA" # evosax.Strategies

SEED: 1

ENV_NAME: "MimicryCommEnvGridworld"
GRID_SIZE: 5
N_AGENTS: 2
N_PREY: 1
N_TOTAL_SOUNDS: 10
N_OVERLAPPING_SOUNDS: 10

# WandB Params
WANDB_MODE: "online"
ENTITY: "drcope"
PROJECT: "jaxmarl-mce"

# Checkpointing
CHECKPOINT_INTERVAL: 20
KEEP_CHECKPOINTS: 3