defaults:
  - override hydra/launcher: slurm_launcher
  - _self_

ALGORITHM: "MAPPO"
SEED: 1

# MAPPO Params
LR: 2e-3
NUM_ENVS: 128 
NUM_STEPS: 128 # must be 128
TOTAL_TIMESTEPS: 8e6
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 4
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
SCALE_CLIP_EPS: False
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
ANNEAL_LR: True

# Env Params
ENV_NAME: "MimicryCommReferentialGame"
N_ACTIONS: 10
EXTERNAL_SOURCE_PROB: 0.5


# WandB Params
WANDB_MODE: "online"
ENTITY: "drcope"
PROJECT: "mimicry-comm-refgame"

# Checkpointing
CHECKPOINT_INTERVAL: 20
KEEP_CHECKPOINTS: 3